// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

var data = /* :: */[
  147129,
  /* :: */[
    128896,
    /* :: */[
      86366,
      /* :: */[
        121702,
        /* :: */[
          106854,
          /* :: */[
            107418,
            /* :: */[
              96021,
              /* :: */[
                116460,
                /* :: */[
                  100395,
                  /* :: */[
                    149526,
                    /* :: */[
                      146314,
                      /* :: */[
                        56215,
                        /* :: */[
                          59911,
                          /* :: */[
                            96016,
                            /* :: */[
                              86483,
                              /* :: */[
                                115837,
                                /* :: */[
                                  84522,
                                  /* :: */[
                                    137658,
                                    /* :: */[
                                      105769,
                                      /* :: */[
                                        149691,
                                        /* :: */[
                                          127499,
                                          /* :: */[
                                            95302,
                                            /* :: */[
                                              53109,
                                              /* :: */[
                                                101940,
                                                /* :: */[
                                                  106343,
                                                  /* :: */[
                                                    140421,
                                                    /* :: */[
                                                      88790,
                                                      /* :: */[
                                                        105898,
                                                        /* :: */[
                                                          68085,
                                                          /* :: */[
                                                            85027,
                                                            /* :: */[
                                                              99405,
                                                              /* :: */[
                                                                116253,
                                                                /* :: */[
                                                                  55338,
                                                                  /* :: */[
                                                                    50009,
                                                                    /* :: */[
                                                                      58244,
                                                                      /* :: */[
                                                                        145865,
                                                                        /* :: */[
                                                                          145270,
                                                                          /* :: */[
                                                                            148777,
                                                                            /* :: */[
                                                                              139954,
                                                                              /* :: */[
                                                                                147397,
                                                                                /* :: */[
                                                                                  128691,
                                                                                  /* :: */[
                                                                                    63082,
                                                                                    /* :: */[
                                                                                      144279,
                                                                                      /* :: */[
                                                                                        76143,
                                                                                        /* :: */[
                                                                                          73006,
                                                                                          /* :: */[
                                                                                            105508,
                                                                                            /* :: */[
                                                                                              62796,
                                                                                              /* :: */[
                                                                                                144807,
                                                                                                /* :: */[
                                                                                                  66587,
                                                                                                  /* :: */[
                                                                                                    50828,
                                                                                                    /* :: */[
                                                                                                      143778,
                                                                                                      /* :: */[
                                                                                                        73793,
                                                                                                        /* :: */[
                                                                                                          76852,
                                                                                                          /* :: */[
                                                                                                            119991,
                                                                                                            /* :: */[
                                                                                                              103181,
                                                                                                              /* :: */[
                                                                                                                105618,
                                                                                                                /* :: */[
                                                                                                                  106320,
                                                                                                                  /* :: */[
                                                                                                                    136345,
                                                                                                                    /* :: */[
                                                                                                                      68771,
                                                                                                                      /* :: */[
                                                                                                                        82534,
                                                                                                                        /* :: */[
                                                                                                                          94528,
                                                                                                                          /* :: */[
                                                                                                                            65802,
                                                                                                                            /* :: */[
                                                                                                                              74863,
                                                                                                                              /* :: */[
                                                                                                                                139414,
                                                                                                                                /* :: */[
                                                                                                                                  65854,
                                                                                                                                  /* :: */[
                                                                                                                                    149543,
                                                                                                                                    /* :: */[
                                                                                                                                      87063,
                                                                                                                                      /* :: */[
                                                                                                                                        85691,
                                                                                                                                        /* :: */[
                                                                                                                                          148931,
                                                                                                                                          /* :: */[
                                                                                                                                            139653,
                                                                                                                                            /* :: */[
                                                                                                                                              90728,
                                                                                                                                              /* :: */[
                                                                                                                                                100710,
                                                                                                                                                /* :: */[
                                                                                                                                                  110159,
                                                                                                                                                  /* :: */[
                                                                                                                                                    131407,
                                                                                                                                                    /* :: */[
                                                                                                                                                      129323,
                                                                                                                                                      /* :: */[
                                                                                                                                                        145874,
                                                                                                                                                        /* :: */[
                                                                                                                                                          127227,
                                                                                                                                                          /* :: */[
                                                                                                                                                            129006,
                                                                                                                                                            /* :: */[
                                                                                                                                                              105828,
                                                                                                                                                              /* :: */[
                                                                                                                                                                67468,
                                                                                                                                                                /* :: */[
                                                                                                                                                                  136905,
                                                                                                                                                                  /* :: */[
                                                                                                                                                                    89273,
                                                                                                                                                                    /* :: */[
                                                                                                                                                                      133439,
                                                                                                                                                                      /* :: */[
                                                                                                                                                                        78783,
                                                                                                                                                                        /* :: */[
                                                                                                                                                                          90794,
                                                                                                                                                                          /* :: */[
                                                                                                                                                                            116324,
                                                                                                                                                                            /* :: */[
                                                                                                                                                                              132792,
                                                                                                                                                                              /* :: */[
                                                                                                                                                                                135413,
                                                                                                                                                                                /* :: */[
                                                                                                                                                                                  142086,
                                                                                                                                                                                  /* :: */[
                                                                                                                                                                                    62659,
                                                                                                                                                                                    /* :: */[
                                                                                                                                                                                      59178,
                                                                                                                                                                                      /* :: */[
                                                                                                                                                                                        59080,
                                                                                                                                                                                        /* :: */[
                                                                                                                                                                                          122465,
                                                                                                                                                                                          /* :: */[
                                                                                                                                                                                            62753,
                                                                                                                                                                                            /* :: */[
                                                                                                                                                                                              112104,
                                                                                                                                                                                              /* :: */[
                                                                                                                                                                                                92551,
                                                                                                                                                                                                /* :: */[
                                                                                                                                                                                                  90638,
                                                                                                                                                                                                  /* :: */[
                                                                                                                                                                                                    145232,
                                                                                                                                                                                                    /* :: */[
                                                                                                                                                                                                      133984,
                                                                                                                                                                                                      /* :: */[
                                                                                                                                                                                                        139994,
                                                                                                                                                                                                        /* [] */0
                                                                                                                                                                                                      ]
                                                                                                                                                                                                    ]
                                                                                                                                                                                                  ]
                                                                                                                                                                                                ]
                                                                                                                                                                                              ]
                                                                                                                                                                                            ]
                                                                                                                                                                                          ]
                                                                                                                                                                                        ]
                                                                                                                                                                                      ]
                                                                                                                                                                                    ]
                                                                                                                                                                                  ]
                                                                                                                                                                                ]
                                                                                                                                                                              ]
                                                                                                                                                                            ]
                                                                                                                                                                          ]
                                                                                                                                                                        ]
                                                                                                                                                                      ]
                                                                                                                                                                    ]
                                                                                                                                                                  ]
                                                                                                                                                                ]
                                                                                                                                                              ]
                                                                                                                                                            ]
                                                                                                                                                          ]
                                                                                                                                                        ]
                                                                                                                                                      ]
                                                                                                                                                    ]
                                                                                                                                                  ]
                                                                                                                                                ]
                                                                                                                                              ]
                                                                                                                                            ]
                                                                                                                                          ]
                                                                                                                                        ]
                                                                                                                                      ]
                                                                                                                                    ]
                                                                                                                                  ]
                                                                                                                                ]
                                                                                                                              ]
                                                                                                                            ]
                                                                                                                          ]
                                                                                                                        ]
                                                                                                                      ]
                                                                                                                    ]
                                                                                                                  ]
                                                                                                                ]
                                                                                                              ]
                                                                                                            ]
                                                                                                          ]
                                                                                                        ]
                                                                                                      ]
                                                                                                    ]
                                                                                                  ]
                                                                                                ]
                                                                                              ]
                                                                                            ]
                                                                                          ]
                                                                                        ]
                                                                                      ]
                                                                                    ]
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var Data = {
  data: data
};

function divideFloatBy3(mass) {
  return mass / 3;
}

function divideIntBy3(mass) {
  return mass / 3 | 0;
}

function roundDown(mass) {
  return mass | 0;
}

function subtractTwo($$int) {
  return $$int - 2 | 0;
}

function main(param) {
  var __x = Belt_List.map(data, (function (prim) {
          return prim;
        }));
  var __x$1 = Belt_List.map(__x, divideFloatBy3);
  var __x$2 = Belt_List.map(__x$1, roundDown);
  var __x$3 = Belt_List.map(__x$2, subtractTwo);
  var result = Belt_List.reduce(__x$3, 0, (function (prim, prim$1) {
          return prim + prim$1 | 0;
        }));
  console.log(result);
  return /* () */0;
}

main(/* () */0);

function main$1(param) {
  var convert = function (value) {
    return (value / 3 | 0) - 2 | 0;
  };
  var __x = Belt_List.map(data, convert);
  var result = Belt_List.reduce(__x, 0, (function (prim, prim$1) {
          return prim + prim$1 | 0;
        }));
  console.log(result);
  return /* () */0;
}

main$1(/* () */0);

function main$2(param) {
  var __x = Belt_List.map(data, divideIntBy3);
  var __x$1 = Belt_List.map(__x, subtractTwo);
  var result = Belt_List.reduce(__x$1, 0, (function (prim, prim$1) {
          return prim + prim$1 | 0;
        }));
  console.log(result);
  return /* () */0;
}

main$2(/* () */0);

exports.Data = Data;
exports.divideFloatBy3 = divideFloatBy3;
exports.divideIntBy3 = divideIntBy3;
exports.roundDown = roundDown;
exports.subtractTwo = subtractTwo;
exports.main = main$2;
/*  Not a pure module */
