// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

var data = /* :: */Caml_chrome_debugger.simpleVariant("::", [
    147129,
    /* :: */Caml_chrome_debugger.simpleVariant("::", [
        128896,
        /* :: */Caml_chrome_debugger.simpleVariant("::", [
            86366,
            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                121702,
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    106854,
                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        107418,
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            96021,
                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                116460,
                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                    100395,
                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                        149526,
                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                            146314,
                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                56215,
                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                    59911,
                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                        96016,
                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                            86483,
                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                115837,
                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                    84522,
                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                        137658,
                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                            105769,
                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                149691,
                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                    127499,
                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                        95302,
                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                            53109,
                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                101940,
                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                    106343,
                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                        140421,
                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                            88790,
                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                105898,
                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                    68085,
                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                        85027,
                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                            99405,
                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                116253,
                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                    55338,
                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                        50009,
                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                            58244,
                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                145865,
                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                    145270,
                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                        148777,
                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                            139954,
                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                147397,
                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                    128691,
                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                        63082,
                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                            144279,
                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                76143,
                                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                    73006,
                                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                        105508,
                                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                            62796,
                                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                144807,
                                                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                    66587,
                                                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                        50828,
                                                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                            143778,
                                                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                73793,
                                                                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                    76852,
                                                                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                        119991,
                                                                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                            103181,
                                                                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                105618,
                                                                                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                    106320,
                                                                                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                        136345,
                                                                                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                            68771,
                                                                                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                82534,
                                                                                                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                    94528,
                                                                                                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                        65802,
                                                                                                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                            74863,
                                                                                                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                139414,
                                                                                                                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                    65854,
                                                                                                                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                        149543,
                                                                                                                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                            87063,
                                                                                                                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                85691,
                                                                                                                                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                    148931,
                                                                                                                                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                        139653,
                                                                                                                                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                            90728,
                                                                                                                                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                100710,
                                                                                                                                                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                    110159,
                                                                                                                                                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                        131407,
                                                                                                                                                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                            129323,
                                                                                                                                                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                145874,
                                                                                                                                                                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                    127227,
                                                                                                                                                                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                        129006,
                                                                                                                                                                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                            105828,
                                                                                                                                                                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                67468,
                                                                                                                                                                                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                    136905,
                                                                                                                                                                                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                        89273,
                                                                                                                                                                                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                            133439,
                                                                                                                                                                                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                78783,
                                                                                                                                                                                                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                    90794,
                                                                                                                                                                                                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                        116324,
                                                                                                                                                                                                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                            132792,
                                                                                                                                                                                                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                                135413,
                                                                                                                                                                                                                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                                    142086,
                                                                                                                                                                                                                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                                        62659,
                                                                                                                                                                                                                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                                            59178,
                                                                                                                                                                                                                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                                                59080,
                                                                                                                                                                                                                                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                                                    122465,
                                                                                                                                                                                                                                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                                                        62753,
                                                                                                                                                                                                                                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                                                            112104,
                                                                                                                                                                                                                                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                                                                92551,
                                                                                                                                                                                                                                                                                                                                                                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                                                                    90638,
                                                                                                                                                                                                                                                                                                                                                                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                                                                        145232,
                                                                                                                                                                                                                                                                                                                                                                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                                                                            133984,
                                                                                                                                                                                                                                                                                                                                                                                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                                                                                                                                                                                                                                                                                                                139994,
                                                                                                                                                                                                                                                                                                                                                                                                                /* [] */0
                                                                                                                                                                                                                                                                                                                                                                                                              ])
                                                                                                                                                                                                                                                                                                                                                                                                          ])
                                                                                                                                                                                                                                                                                                                                                                                                      ])
                                                                                                                                                                                                                                                                                                                                                                                                  ])
                                                                                                                                                                                                                                                                                                                                                                                              ])
                                                                                                                                                                                                                                                                                                                                                                                          ])
                                                                                                                                                                                                                                                                                                                                                                                      ])
                                                                                                                                                                                                                                                                                                                                                                                  ])
                                                                                                                                                                                                                                                                                                                                                                              ])
                                                                                                                                                                                                                                                                                                                                                                          ])
                                                                                                                                                                                                                                                                                                                                                                      ])
                                                                                                                                                                                                                                                                                                                                                                  ])
                                                                                                                                                                                                                                                                                                                                                              ])
                                                                                                                                                                                                                                                                                                                                                          ])
                                                                                                                                                                                                                                                                                                                                                      ])
                                                                                                                                                                                                                                                                                                                                                  ])
                                                                                                                                                                                                                                                                                                                                              ])
                                                                                                                                                                                                                                                                                                                                          ])
                                                                                                                                                                                                                                                                                                                                      ])
                                                                                                                                                                                                                                                                                                                                  ])
                                                                                                                                                                                                                                                                                                                              ])
                                                                                                                                                                                                                                                                                                                          ])
                                                                                                                                                                                                                                                                                                                      ])
                                                                                                                                                                                                                                                                                                                  ])
                                                                                                                                                                                                                                                                                                              ])
                                                                                                                                                                                                                                                                                                          ])
                                                                                                                                                                                                                                                                                                      ])
                                                                                                                                                                                                                                                                                                  ])
                                                                                                                                                                                                                                                                                              ])
                                                                                                                                                                                                                                                                                          ])
                                                                                                                                                                                                                                                                                      ])
                                                                                                                                                                                                                                                                                  ])
                                                                                                                                                                                                                                                                              ])
                                                                                                                                                                                                                                                                          ])
                                                                                                                                                                                                                                                                      ])
                                                                                                                                                                                                                                                                  ])
                                                                                                                                                                                                                                                              ])
                                                                                                                                                                                                                                                          ])
                                                                                                                                                                                                                                                      ])
                                                                                                                                                                                                                                                  ])
                                                                                                                                                                                                                                              ])
                                                                                                                                                                                                                                          ])
                                                                                                                                                                                                                                      ])
                                                                                                                                                                                                                                  ])
                                                                                                                                                                                                                              ])
                                                                                                                                                                                                                          ])
                                                                                                                                                                                                                      ])
                                                                                                                                                                                                                  ])
                                                                                                                                                                                                              ])
                                                                                                                                                                                                          ])
                                                                                                                                                                                                      ])
                                                                                                                                                                                                  ])
                                                                                                                                                                                              ])
                                                                                                                                                                                          ])
                                                                                                                                                                                      ])
                                                                                                                                                                                  ])
                                                                                                                                                                              ])
                                                                                                                                                                          ])
                                                                                                                                                                      ])
                                                                                                                                                                  ])
                                                                                                                                                              ])
                                                                                                                                                          ])
                                                                                                                                                      ])
                                                                                                                                                  ])
                                                                                                                                              ])
                                                                                                                                          ])
                                                                                                                                      ])
                                                                                                                                  ])
                                                                                                                              ])
                                                                                                                          ])
                                                                                                                      ])
                                                                                                                  ])
                                                                                                              ])
                                                                                                          ])
                                                                                                      ])
                                                                                                  ])
                                                                                              ])
                                                                                          ])
                                                                                      ])
                                                                                  ])
                                                                              ])
                                                                          ])
                                                                      ])
                                                                  ])
                                                              ])
                                                          ])
                                                      ])
                                                  ])
                                              ])
                                          ])
                                      ])
                                  ])
                              ])
                          ])
                      ])
                  ])
              ])
          ])
      ])
  ]);

var Data = {
  data: data
};

function divideFloatBy3(mass) {
  return mass / 3;
}

function divideIntBy3(mass) {
  return mass / 3 | 0;
}

function roundDown(mass) {
  return mass | 0;
}

function subtractTwo($$int) {
  return $$int - 2 | 0;
}

function main(param) {
  var __x = Belt_List.map(data, (function (prim) {
          return prim;
        }));
  var __x$1 = Belt_List.map(__x, divideFloatBy3);
  var __x$2 = Belt_List.map(__x$1, roundDown);
  var __x$3 = Belt_List.map(__x$2, subtractTwo);
  var result = Belt_List.reduce(__x$3, 0, (function (prim, prim$1) {
          return prim + prim$1 | 0;
        }));
  console.log(result);
  return /* () */0;
}

main(/* () */0);

function main$1(param) {
  var convert = function (value) {
    return (value / 3 | 0) - 2 | 0;
  };
  var __x = Belt_List.map(data, convert);
  var result = Belt_List.reduce(__x, 0, (function (prim, prim$1) {
          return prim + prim$1 | 0;
        }));
  console.log(result);
  return /* () */0;
}

main$1(/* () */0);

function main$2(param) {
  var __x = Belt_List.map(data, divideIntBy3);
  var __x$1 = Belt_List.map(__x, subtractTwo);
  var result = Belt_List.reduce(__x$1, 0, (function (prim, prim$1) {
          return prim + prim$1 | 0;
        }));
  console.log(result);
  return /* () */0;
}

main$2(/* () */0);

exports.Data = Data;
exports.divideFloatBy3 = divideFloatBy3;
exports.divideIntBy3 = divideIntBy3;
exports.roundDown = roundDown;
exports.subtractTwo = subtractTwo;
exports.main = main$2;
/*  Not a pure module */
