// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

var test_values = /* :: */Caml_chrome_debugger.simpleVariant("::", [
    2,
    /* :: */Caml_chrome_debugger.simpleVariant("::", [
        4,
        /* :: */Caml_chrome_debugger.simpleVariant("::", [
            4,
            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                5,
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    99,
                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        0,
                        /* [] */0
                      ])
                  ])
              ])
          ])
      ])
  ]);

function compute(input_values, _input_value_index) {
  while(true) {
    var input_value_index = _input_value_index;
    var process_this_value = List.nth(input_values, input_value_index);
    if (process_this_value !== 99) {
      _input_value_index = input_value_index + 1 | 0;
      continue ;
    } else {
      return 0;
    }
  };
}

function divideBy3(mass) {
  return mass / 3;
}

function roundDown(mass) {
  return mass | 0;
}

function subtractTwo($$int) {
  return $$int - 2 | 0;
}

function convert(_value) {
  while(true) {
    var value = _value;
    var converted = (value / 3 | 0) - 2 | 0;
    console.log("converted", converted);
    var match = converted >= 0;
    if (match) {
      _value = converted;
      continue ;
    } else {
      return /* () */0;
    }
  };
}

function convertListHd(_list) {
  while(true) {
    var list = _list;
    console.log(list);
    console.log("intial", 0);
    var match = Belt_List.length(list);
    if (match !== 0) {
      Belt_List.headExn(list);
      var __x = convert(Belt_List.headExn(list));
      console.log("lshd", __x);
      _list = Belt_List.tailExn(list);
      continue ;
    } else {
      return /* () */0;
    }
  };
}

function main(param) {
  console.log("Hello, Day 2!");
  console.log(compute(test_values, 0));
  console.log(convert(99));
  return convertListHd(test_values);
}

exports.test_values = test_values;
exports.compute = compute;
exports.divideBy3 = divideBy3;
exports.roundDown = roundDown;
exports.subtractTwo = subtractTwo;
exports.convert = convert;
exports.convertListHd = convertListHd;
exports.main = main;
/* No side effect */
