// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Day1$AdventOfCode = require("./Day1.bs.js");
var Day2$AdventOfCode = require("./Day2.bs.js");

console.log("Hello, BuckleScript and Reason Advent of Code!");

Day1$AdventOfCode.main(/* () */0);

Day2$AdventOfCode.main(/* () */0);

/*  Not a pure module */
